# The delay for loading autorun scripts (in ticks) after the plugin loads.
script-load-delay: 20
# If true, PySpigot will import the org.bukkit.Bukkit object (wrapper for org.bukkit.Server) into every script so that you do not have to import it yourself.
auto-import-bukkit: false
#List of relocation rules for libraries in the libs folder. Format as <pattern>|<relocated pattern>
library-relocations: []
messages:
  plugin-prefix: '&8[&6PySpigot&8] &r'