# The delay for loading autorun scripts (in ticks) after the plugin loads.
script-load-delay: 20
#List of relocation rules for libraries in the libs folder. Format as <pattern>|<relocated pattern>
library-relocations: []
messages:
  plugin-prefix: '&8[&6PySpigot&8] &r'